### ISSUE TITLE
Better formatting on the message

### ISSUE THREAD

**Issue by linjunpop** [Hazyzh/sfCase2jira-RCINT#2]
Currently, the message displays in a single line:

https://github.com/Hazyzh/sfCase2jira-RCINT/blob/f3c86885e6019a31a2e4db2de49fd77f576c035b/src/component/EditModal.tsx#L57

And it causes the Jira link hard to copy & navigate to.

It would be nice if the Jira ticket's link can be easily copied: 

- by displaying it on its own line, so a double click on the URL can select all texts to be copied
- or added a button to copy the URL programmatically

Also, it would be great if the link can navigate with a single click, ex. by wrapping with `<a></a>`

**Comment by Hazyzh** [comment]
Cool, will add those features.
